name: CI Dev Branch

on:
  push:
    branches: [dev]

jobs:
  build-dotnet-8:
    uses: ./.github/workflows/reusable-build.yml
    with:
      dotnet-version: '8.0'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  build-dotnet-9:
    uses: ./.github/workflows/reusable-build.yml
    with:
      dotnet-version: '9.0'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}